[project]
name = "moomoo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "pillow>=11.3.0",
    "requests>=2.32.5",
]
